#
# Azure Pipeline - Generic build defintion for containerized apps
# Build as Docker container image and push to ACR
# Ben C, 2019
#
trigger: 
  branches:
    include: [ master ] 

pool:
  name: Hosted Ubuntu 1604

#
# NOTE! - Expected secret variables: acr-password
# Must use the Azure Pipelines UI to create this before pipeline will run!
#
variables:
  - name: imagename
    value: nodejs-demoapp
  - name: acr-name
    value: CHANGEME
  - name: docker-file
    value: Dockerfile

steps:
#
# Run Docker build
#
- bash: |
    docker build . -f $(docker-file) -t $(acr-name).azurecr.io/$(imagename):latest -t $(acr-name).azurecr.io/$(app-name):$(Build.BuildNumber)
  displayName: 'Build app as container image'

#
# Push latest + tagged images to ACR
#
- bash: |
    docker login $(acr-name).azurecr.io -u $(acr-name) -p $(acr-password)
    docker push $(acr-name).azurecr.io/apps/$(app-name)
  displayName: 'Push image to ACR'