trigger: none

#
# NOTE! The shared-secrets variable group must be pre-created and populated
# - Expected variables: acr-password
#
variables:
  - group: shared-secrets

  - name: app-name
    value: 'nodejs-demoapp'
  - name: res-group
    value: 'Demo.AppService'
  - name: azure-connection
    value: 'Azure (AIRS)'
  - name: acr-name
    value: 'bcdemo'
  - name: appservice-plan
    value: 'SharedAppPlanLinux'
  - name: location
    value: 'North Europe'

stages:
- stage: deployTest
  displayName: 'Test'
  variables:
    appservice-name: '$(app-name)-test'
  jobs:
  - template: templates/arm-app-service.yml
    parameters:
      envName: Test

- stage: deployStaging
  displayName: 'Staging'
  variables:
    appservice-name: '$(app-name)-staging'
  jobs:
  - template: templates/arm-app-service.yml
    parameters:
      envName: Staging