name: Build & Deploy AKS

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]
    
env:
  dockerUser: bencuk
  acrName: bcdemo
  imageName: nodejs-demoapp
  imageTag: latest
  
jobs:
  buildJob:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag $dockerUser/$imageName:$imageTag --tag $acrname.azurecr.io/apps/$imageName:$imageTag
    
    - name: Login to Dockerhub
      run: docker login -u $dockerUser -p ${{ secrets.dockerPassword }} 
      
    - name: Push to Dockerhub
      run: docker push $dockerUser/$imageName:$imageTag
