name: CD Release - Bicep

on:
  push:
    branches: [master]
  workflow_dispatch:

# Note. Required secrets: CR_PAT & AZURE_CREDENTIALS

env:
  IMAGE_REG: ghcr.io
  IMAGE_REPO: benc-uk/nodejs-demoapp
  APP_NAME: nodeappbc
  ARM_SUB_ID: 52512f28-c6ed-403e-9569-82a9fb9fec91
  ARM_REGION: northeurope
  ARM_RES_GROUP: release-nodejs-demoapp

jobs:
  #
  # Run the image build & push to registry
  #
  build-app:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build image
        run: docker build . -t $IMAGE_REG/$IMAGE_REPO:${{ github.run_id }} -t $IMAGE_REG/$IMAGE_REPO:latest

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REG }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker push image to ${{ env.IMAGE_REG }}
        run: docker push $IMAGE_REG/$IMAGE_REPO

  #
  # Deploy Azure infra using Bicep
  #
  deploy-bicep:
    name: Deploy Infra
    needs: build-app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep compiler
        run: |
          wget https://github.com/Azure/bicep/releases/download/v0.1.37-alpha/bicep-linux-x64 -qO bicep
          chmod +x bicep
          ./bicep build webapp.bicep
        working-directory: ./infra

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        run: az group create --name ${{ env.ARM_RES_GROUP }} --location ${{ env.ARM_REGION }}

      - name: Deploy resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.ARM_SUB_ID }}
          resourceGroupName: ${{ env.ARM_RES_GROUP }}
          template: ./infra/webapp.json
          parameters: webappName=${{ env.APP_NAME }} webappImage=${{ env.IMAGE_REG }}/${{ env.IMAGE_REPO }}:${{ github.run_id }} weatherKey=${{ secrets.WEATHER_API_KEY }}
          deploymentName: webapp-deploy-${{ github.run_id }}

  #
  # Post deployment testing stage
  #
  validate-deployment:
    name: Smoke Test App Deployment
    needs: deploy-bicep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate site is running
        run: .github/scripts/url-check.sh -u https://${{ env.APP_NAME }}.azurewebsites.net/ -s "Ben Coleman" -t 200
