name: CI Build App

on:
  # push:
  #   branches-ignore: [master]
  pull_request:

jobs:
  test:
    name: Tests & Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM install
        run: npm install --silent
        working-directory: ./src

      - name: Run linting
        run: npm run lint
        working-directory: ./src

      - name: Run tests
        run: npm run test-junit
        working-directory: ./src

      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./src/test-results.xml

  build:
    name: Build Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: docker build . -t temp-ci-image
